CREATE TABLE veiculo (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	veiculo varchar(150),
	marca varchar(100),
	ano integer,
	descricao varchar(255),
	vendido BOOL,
	created timestamp,
	updated timestamp
);